# Generated by Django 3.2.4 on 2022-07-24 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=512)),
                ('word_id', models.CharField(max_length=64, unique=True)),
                ('reading_form', models.CharField(max_length=512)),
                ('normalized_form', models.CharField(max_length=512)),
                ('lemma', models.CharField(max_length=512)),
                ('part_of_speech', models.CharField(max_length=32)),
                ('kanji', models.CharField(max_length=256)),
                ('furigana', models.CharField(max_length=256)),
                ('okurigana', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WordCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcollection.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
